# Generated by Django 4.2.3 on 2024-11-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0003_alter_product_brand_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
